### ISSUE TITLE
请问代码还维护吗？我这边遇到一个bug

### ISSUE THREAD

**Issue by xlz122** [anthinkingcoder/vue-wheel-number#1]
第一种动画，情景如下： 666->888,动画正常，888->2222出现bug（会出现888->2220的结果）,也就是增加一位数的时候，最后一位数动画不生效，停留在0

**Comment by anthinkingcoder** [comment]
不维护了，这个代码你参照下优化下就可以了，很久以前的了。你这个问题是因为有个样式被原始样式覆盖了，已经解决了。

**Comment by xlz122** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhoulin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月29日(星期天) 晚上9:56
收件人:&nbsp;"anthinkingcoder/vue-wheel-number"<vue-wheel-number@noreply.github.com&gt;;
抄送:&nbsp;"撇捺"<122874722@qq.com&gt;;"Manual"<manual@noreply.github.com&gt;;
主题:&nbsp;Re: [anthinkingcoder/vue-wheel-number] 请问代码还维护吗？我这边遇到一个bug (#1)




不维护了，这个代码你参照下优化下就可以了，很久以前的了。你这个问题是因为有个样式被原始样式覆盖了，已经解决了。
